### ISSUE TITLE
doesn't build with prometheus/client_golang:master

### ISSUE THREAD

**Issue by sezuan** [imgix/prometheus-am-executor#10]
See https://github.com/prometheus/client_golang/pull/600. The prometheus.Handler() function has been removed.

**Comment by danielkoo** [comment]
from a quick look I believe promhttp should be used instead, I am new to this, but could have a look if there's no one else?

**Comment by otakup0pe** [comment]
I want to test a bit more than I have but will be merging #9 once that is done.

**Comment by hartfordfive** [comment]
Any updates on merging the fix for this?  I'd rather use this library instead of forking my own to add my own fix.
:+1:
