### ISSUE TITLE
Refactor main.go, to use a config struct instead of global vars

### ISSUE THREAD

**Issue by colakong** [imgix/prometheus-am-executor#18]
This will
* help make `handleWebhook` easier to test
* unblock development of some other features

**Comment by otakup0pe** [comment]
We should probably support falling back to the env vars at least for a period of time. This would make the transition to new config format easier.

**Comment by colakong** [comment]
For some context on this issue and some of the following ones, this issue is meant to implement something like this:
```go
type Config struct {
    listenAddr string
    verbose bool
    processDuration prometheus.Histogram
    processesCurrent prometheus.Gauge
    errCounter *prometheus.CounterVec
    rnr *runner
}

func (cfg *Config) handleWebhook(w http.ResponseWriter, req *http.Request) {
    cfg.rnr.run(...)
}

func main() {
    c := Config{
        ...
    }

    http.HandleFunc("/", c.handleWebhook)
}
```

We're passing the same function (now a method) to `http.HandleFunc`, but we can customize its behaviour with the `Config` struct. This is meant to make it easier to use `handleWebhook` in a test (#19)

Then in issue #20, we can populate values in the `Config` struct from a config file. In #21, we add support for config file sections, that specify executing different commands based on matching alarm labels. The same `AMX_` env vars are still provided for those commands.

Issue #24 talks about adding functionality for providing alarm data to a command via STDIN. We can make it so that the `AMX_` env vars are provided to a command, regardless of if STDIN was selected.
