### ISSUE TITLE
run multiple script file

### ISSUE THREAD

**Issue by bientt210** [imgix/prometheus-am-executor#28]
Hi Everyone,

I want to run with multiple script but i don't know how to run or how to run multiple command once time? can everyone help me.

Thanks you so much!

**Comment by colakong** [comment]
Hi @bientt210, currently you'd need to run multiple instances of prometheus-am-executor, each configured to run a different command.

This is pretty limiting, so there's a ticket open for updating the code to allow running multiple commands, dispatching to them based on alarm labels. (#21). I'll implement it after working on #20, as time permits :)

**Comment by bientt210** [comment]
Thanks for your answer,

So i need to run as a service in systemD, can you give me a template for run as a service

Thanks you so much!
