### ISSUE TITLE
Allow for command delays when matching alarms/alarm entities exceeds a threshold in a time-frame

### ISSUE THREAD

**Issue by colakong** [imgix/prometheus-am-executor#32]
This issue is to add functionality to introduce delays in executing a particular command, if
* the number of matching alarms within a time-frame exceeds a threshold, and/or
* the number of unique entities in the matching alarms within a time-frame exceeds a threshold

An example of a use-case is that if you are executing a command that manages the state of a fleet of services, you want to control how much of the fleet that is affected at the same time if you received an alarm that affects the entire fleet. This is helpful for avoiding situations where a problem in monitoring itself triggers an issue by applying an operation to an entire fleet at the same time.

**Comment by ultimatealf** [comment]
Have we seen any of these types of issues with our monitoring stack in the past?

**Comment by colakong** [comment]
> Have we seen any of these types of issues with our monitoring stack in the past?

Not to my knowledge. I've witnessed this sort of problem at other organizations though.

**Comment by colakong** [comment]
I decided to handle this with the `max` command config option; It provides a limit for the number of identical commands running for an alarm at the same time.
