### ISSUE TITLE
Support cancelling running command for an alarm if a resolve condition is received.

### ISSUE THREAD

**Issue by colakong** [imgix/prometheus-am-executor#34]
If we receive a message indicating that an alarm was 'resolved', we could support killing the processes that were run for that alarm.

**Comment by otakup0pe** [comment]
This would be to handle things which act more like a service than a one off?

**Comment by colakong** [comment]
> This would be to handle things which act more like a service than a one off?

Yes it would be meant to handle cancelling commands that stay running for a while (like a command that retries on failure and has a long timer in-between retries)
