### ISSUE TITLE
Add ability to kill exec process with SIGTERM instead of SIGKILL when resolved alert arrived

### ISSUE THREAD

**Issue by spigell** [imgix/prometheus-am-executor#37]
Greetings. I think it will be useful if one may use SIGTERM instead of SIGKILL via configuration file (since it not supported on all OSes).

**Comment by otakup0pe** [comment]
Being able to specify the signal sent makes sense. I can even thing of cases where SIGHUP or SIGUSR1 (sometimes used to dump debug info) would be helpful.
