### ISSUE TITLE
MacOS with Go throwing error "undefined: syscall.SIGCLD" and similar error

### ISSUE THREAD

**Issue by tan31989** [imgix/prometheus-am-executor#41]
While building the project in MacOS (`11.1`) and Go version (`go version go1.14.3 darwin/amd64`), I am seeing the following error of undefined Signal:

```sh
$ go build .
# github.com/imgix/prometheus-am-executor
./command.go:40:16: undefined: syscall.SIGCLD
./command.go:50:16: undefined: syscall.SIGPOLL
./command.go:52:16: undefined: syscall.SIGPWR
./command.go:55:16: undefined: syscall.SIGSTKFLT
./command.go:63:16: undefined: syscall.SIGUNUSED
```

Once I removed the mentioned signals from `command.go`, it was built successfully.

**Comment by tan31989** [comment]
@colakong can I raise a PR which eventually can remove this signal's from the `command.go` file?

**Comment by colakong** [comment]
Thank you for raising this issue. We would have been able to catch this if we had CI setup for linux and macOS targets.

> @colakong can I raise a PR which eventually can remove this signal's from the `command.go` file?

Of course you can ^^. I've done this in PR #42.

**Comment by colakong** [comment]
[Version 2.0.1](https://github.com/imgix/prometheus-am-executor/tree/v2.0.1) has the unsupported macOS signals removed. Users can use the integer form of those signals if they still want to specify them on non-macOS platforms.
