### ISSUE TITLE
Unable to run prometheus-am-executor.

### ISSUE THREAD

**Issue by asking28** [imgix/prometheus-am-executor#5]
I have cloned prometheus-am-executor to my directory. And then I run ~/.prometheus-am-executor it does not work. I have already configured Prometheus and alertmanager. Help me how to do it.

**Comment by Priyotosh008** [comment]
Hello Abhishek,

Are you able to run prometheus-am-executor ?

**Comment by asking28** [comment]
Yes

**Comment by Priyotosh008** [comment]
Can you please help me on how to start prometheus-am-executor ?

**Comment by asking28** [comment]
You have to write shell script that you want to run and then use the above command

**Comment by Priyotosh008** [comment]
I didn't got what you meant by this.
If you don't mind can you please give me an example. I'm totally lost here.
I have configured prometheus, alertmanager and successfully receiving email alerts from alertmanager.

Not quite sure on how this exporter will trigger a script.

**Comment by asking28** [comment]
Check this [https://github.com/asking28/resource-monitoring/wiki/Prometheus-am-executor](https://github.com/asking28/resource-monitoring/wiki/Prometheus-am-executor) link. It will guide you. I have documeented the steps that I followed.

**Comment by Priyotosh008** [comment]
Thank you for the URL.

This means we need to install go for this exporter to function ?
Sorry I don't have any idea on go language.

Do we need to run **go build** for this exporter to run ?
I have already unzipped the exporter in my linux machine. But unable to start it and invoke a script.

**Comment by asking28** [comment]
Yes, we need to go to build this.

**Comment by Manianbalagan** [comment]
Folks,

I have cloned package and unzipped it . But i dont see the ./prometheus-am-executor executable inside it .
