### ISSUE TITLE
Is this an active project ?

### ISSUE THREAD

**Issue by arjunnath** [imgix/prometheus-am-executor#7]
Hi, 
Is this an active project  ?
There seems to be no development for a long time.
Is there a similar project somewhere ?

thanks

**Comment by davidbirdsong** [comment]
all the maintainers have moved on from imgix and it's not been abundantly
clear that it's a useful project, though in theory it definitely can be.

**Comment by arjunnath** [comment]
Thanks for the quick response. We have a need for this and were were working on a similar tool before coming across this. We could potentially contribute back some code.

**Comment by davidbirdsong** [comment]
I'm not actively working in a prometheus shop myself, but maybe moving
towards that soon. I do have some amount of familiarity with the code--it's
pretty straightforward.

I'd give it a try, if you find room for improvement, submit a PR and ping
me. I'll see if I can get their attention and maybe get added as an owner.

@Johannes Ziemke <fish@freigeist.org> got any interest in maintenance?

**Comment by otakup0pe** [comment]
Pull requests would be welcome 💖

**Comment by discordianfish** [comment]
Looks like this fork even has CI setup: https://github.com/thiagoalmeidasa/prometheus-am-executor
If @thiagoalmeidasa has interest in maintaining that, we can declare that the 'official' fork.

**Comment by arjunnath** [comment]
is that code identical besides the CI setup ?

**Comment by discordianfish** [comment]
@arjunnath You can see the diff here: https://github.com/imgix/prometheus-am-executor/compare/master...thiagoalmeidasa:master

**Comment by discordianfish** [comment]
I'd suggest using go modules than installing deps like that. But if @thiagoalmeidasa doesn't want to maintain it, I'd still maintain my fork on a best effort base if somebody wants to use it and submit PRs: https://github.com/discordianfish/prometheus-am-executor

**Comment by otakup0pe** [comment]
We are once again using this, and have setup CI. PR's (and further future discussion) certainly welcome 💖

**Comment by aantn** [comment]
Hey all, I develop an open source project that does something similar and is actively maintained.

What we do is more broad than `prometheus-am-executor` because it supports many triggers other than just Prometheus/AlertManager. It also has builtin high-level actions like "restart pod", "fetch logs", etc.

Would it be cool to post a link here to our Github? I don't want to spam this thread, but I think it could be useful to some people reading this.

**Comment by colakong** [comment]
Hi @aantn, yes I think that would be fine. Once you paste a link I'll update the main README with something to the same effect :)

**Comment by aantn** [comment]
@colakong thank you!

It's https://github.com/robusta-dev/robusta or https://docs.robusta.dev/master/

**Comment by colakong** [comment]
> @colakong thank you!
> 
> It's https://github.com/robusta-dev/robusta or https://docs.robusta.dev/master/

A note has been placed via PR #48 :)
