### ISSUE TITLE
Getting error at webhook url

### ISSUE THREAD

**Issue by dhiren051** [imgix/prometheus-am-executor#8]
Build executor and triggered alert for testing but got this error at URL

"unexpected end of JSON input"

**Comment by otakup0pe** [comment]
Hmm what did you use for the sample JSON? The integration test is pretty basic but does have [one](https://github.com/imgix/prometheus-am-executor/blob/master/scripts/integration#L17) sample JSON blob.

**Comment by dhiren051** [comment]
I didn't change anything in the integration script. Set node exporter down alert in yaml and webhook receiver. Do I have to set alert in json format or change default json blob intigration ?

**Comment by dhiren051** [comment]
> Hmm what did you use for the sample JSON? The integration test is pretty basic but does have [one](https://github.com/imgix/prometheus-am-executor/blob/master/scripts/integration#L17) sample JSON blob.

This is the sample blob I used in integration:
{"receiver":"PrometheusExportersAlert","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"PrometheusExportersAlert","instance":"localhost:9107","job":"consul-exporter"},"annotations":{}}],"groupLabels":{"alertname":"PrometheusExportersAlert"},"commonLabels":{"alertname":"PrometheusExportersAlert","job":"consul-exporter"},"commonAnnotations":{},"externalURL":"http://localhost:9093","version":"3","groupKey":"{}:{alertname=\"PrometheusExportersAlert\", job=\"PrometheusExportersAlert\"}"}

upon running "make all" I do get OK output but at webhook url still getting response: 
unexpected end of JSON input

and got this log: 
2019/04/29 16:57:57 Listening on :8080 and running [./script-test.sh]
2019/04/29 16:58:25 Webhook triggered
2019/04/29 16:58:25 Body:
2019/04/29 16:58:25 unexpected end of JSON input
2019/04/29 16:58:25 Got: &template.Data{Receiver:"", Status:"", Alerts:template.Alerts(nil), GroupLabels:template.KV(nil), CommonLabels:template.KV(nil), CommonAnnotations:template.KV(nil), ExternalURL:""}

health status looks good : 
http://localhost:8080/_health
All systems are functioning within normal specifications.

**Comment by otakup0pe** [comment]
[this](https://github.com/imgix/prometheus-am-executor/blob/master/scripts/integration#L17) is what the integration script uses as a quick test.  It follows the spec defined [here](https://prometheus.io/docs/alerting/configuration/#webhook_config) although it _is_ for an older version (v3 as opposed to the current v4).

The JSON you included in your issue seems off. If this wasn't a copy/paste error, that could be it.

**Comment by dhiren051** [comment]
tried with version 4, no luck. closing ticket here.

**Comment by dhiren051** [comment]
Thanks to Tim. Followed steps from below link and it worked . 
https://groups.google.com/forum/#!msg/prometheus-users/ThmiD2DeyXc/3JEIf-loDQAJ
